Repository brazil-data-cube/wlts, pull requests merged in 2021-02, with the labels that each got.

#36 Fixing get_coverage validation #35 and adding depends on INSTALL
  .drone.yml
  INSTALL.rst
  run-tests.sh
  wlts/collections/image_collection.py
  wlts/datasources/wcs.py
  wlts/utils.py
Labels: bug, documentation

#40 Add integration with docker registry and auto deploy
  .drone.yml
  DEPLOY.rst
  Dockerfile
  MANIFEST.in
  docker-compose.yml
  wlts/version.py
Labels: test

#41 Fix dependency version for OWSlib 0.21.0
  setup.py
Labels: bug
