Repository brazil-data-cube/wlts, pull requests merged in 2021-03, with the labels that each got.

#43 Review WLTS API tests and remove unused sql
  run-tests.sh
  tests/test_app.py
  wlts/__init__.py
  wlts/controller.py
  wlts/example/wlts_example.sql
  wlts/jsonschemas/describe_collection_response.json
  wlts/jsonschemas/trajectory_response.json
  wlts/trajectory.py
Labels: test

#44 adding geometry column in trajectory ref #21
  wlts/collections/class_system.py
  wlts/collections/collection.py
  wlts/collections/feature_collection.py
  wlts/collections/image_collection.py
  wlts/controller.py
  wlts/datasources/wcs.py
  wlts/datasources/wfs.py
  wlts/jsonschemas/trajectory_response.json
  wlts/trajectory.py
  wlts/utils.py
Labels: enhancement

#47 updating Dockerfile
  Dockerfile
Labels: bug
