Repository brazil-data-cube/wlts, pull requests merged in 2022-04, with the labels that each got.

#80 adding datasource informations in describe op
  wlts/collections/collection.py
  wlts/collections/feature_collection.py
  wlts/collections/image_collection.py
  wlts/controller.py
  wlts/datasources/wcs.py
  wlts/datasources/wfs.py
  wlts/utils/jsonschemas/describe_collection_response.json
  wlts/version.py
Labels: enhancement

#82 :sparkles: adding external host information
  wlts/datasources/wcs.py
  wlts/datasources/wfs.py
  wlts/json_configs/datasources.json
Labels: enhancement

#84 :zap: improve datasource information
  wlts/collections/feature_collection.py
  wlts/collections/image_collection.py
  wlts/controller.py
  wlts/utils/jsonschemas/describe_collection_response.json
Labels: documentation, enhancement

#86 Merge branch B 0.9 into master
  CHANGES.rst
  wlts/collections/collection.py
  wlts/collections/feature_collection.py
  wlts/collections/image_collection.py
  wlts/controller.py
  wlts/datasources/wcs.py
  wlts/datasources/wfs.py
  wlts/json_configs/datasources.json
  wlts/utils/jsonschemas/describe_collection_response.json
  wlts/version.py
Labels: release
